services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ROUTER_ENDPOINT=${ROUTER_ENDPOINT}
      - ROUTER_PASSWORD=${ROUTER_PASSWORD}
      - BROWSER_URL=http://172.30.0.20:9222
    depends_on:
      - chrome
    networks:
      rede_interna:
        ipv4_address: 172.30.0.10

  chrome:
    hostname: chrome
    image: chromedp/headless-shell
    restart: unless-stopped
    networks:
      rede_interna:
        ipv4_address: 172.30.0.20
networks:
  rede_interna:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1