services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ROUTER_ENPOINT=${ROUTER_ENPOINT}
      - ROUTER_PASSWORD=${ROUTER_PASSWORD}
      - LIGHTPANDA_URL=http://lightpanda:9222
    depends_on:
      - lightpanda

  lightpanda:
    image: lightpanda/browser:nightly
    restart: unless-stopped
    command: lightpanda serve --host 0.0.0.0 --port 9222
    ports:
      - '127.0.0.1:9222:9222'
