name: pr-agent-review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, review_requested]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: PR Agent Action Step
        uses: the-pr-agent/pr-agent@v0.36.0
        id: pr_agent
        env:
          config.model: "openrouter/anthropic/claude-3.7-sonnet"
          OPENROUTER.KEY: ${{ secrets.OPENROUTER_API_KEY }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
          github_action_config.pr_actions: '["opened", "reopened", "ready_for_review", "review_requested", "synchronize"]'
